# Generated by Django 5.0 on 2024-03-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.AlterModelTable(
            name='user',
            table='User',
        ),
    ]
