# Generated by Django 5.0 on 2024-04-26 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_email_user_email_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='people',
        ),
    ]
