# Generated by Django 5.0 on 2024-04-29 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_temp1_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='temp1',
            table='Weather',
        ),
    ]
