# Generated by Django 5.0 on 2024-04-27 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_temp1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='temp1',
        ),
    ]
